name: PROS Build Action

on: 
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install gcc-arm-linux-gnueabi
      - run: pip install pros-cli
      - run: pros make --verbose
